<?php
// $Id$

/**
 * @file
 * 
 * Provides an agent based model archive within the Drupal framework.  This
 * involves the user creation of new model projects, ability to upload new
 * versions of an ABM project and edit associated metadata.  Members of a
 * review committee should also be able to "star" an ABM project to signify
 * its level of maturity and completeness.
 * 
 *
 */
function openabmma_block ($op='list', $delta=0)
{
	// listing of blocks, such as on the admin/block page
	if ($op == "list")
	{
		$block[0]["info"] = t("OpenABM Resource Links");
		return $block;
	}
	else if ($op == 'view')
	{
		$block_content = l ("My projects", "models/") . "<br/>"
			. l ("Manage project members", "models/members/") . "<br/>"
			;

		if (user_access ('administer content'))
		{
			$block_content .= "<br/>" . l ("Project licenses", "licenses") . "<br/>";
			$block_content .= "<br/>" . l ("Member roles", "roles") . "<br/>";
		}
		$block['subject'] = 'OpenABM Links';
		$block['content'] = $block_content;
		return $block;
	}
}

function openabmma_menu($may_cache) {

    $items = array();
    if ($may_cache) {
        // admin settings for model archive.  Right now I can only think of
        // group membership in the review committee as a configurable option.
        $items[] = array(
            'path' => 'admin/settings/openabmma',
            'title' => t('OpenABM Model Archive Settings'),
            'description' => t('Change model archive settings.'),
            'callback' => 'drupal_get_form',
            'callback arguments' => array('openabmma_settings_form'),
            'type' => MENU_CALLBACK,
            'access' => user_access('administer site configuration')
            );

        $items[] = array(
            'path' => 'models/add',
            'title' => t('Add a new model'),
            'description' => t('Add a new model to the model archive.'),
            'access' => user_access ('access content'),
            'callback' => 'drupal_get_form',
            'type' => MENU_CALLBACK,
            'callback arguments' => array('openabmma_newModel'),
            );

        $items[] = array(
            'path' => 'models',
            'title' => t('My projects'),
            'description' => "",
            'access' => user_access ('access content'),
            'callback' => 'openabmma_showProjects',
            'type' => MENU_CALLBACK
            );

        $items[] = array(
            'path' => 'roles',
            'title' => t('User roles'),
            'description' => "",
            'access' => user_access ('access content'),
            'callback' => 'openabmma_showRoles',
            'type' => MENU_CALLBACK
            );

        $items[] = array(
            'path' => 'licenses',
            'title' => t('Manage licenses'),
            'description' => "",
            'access' => user_access ('administer content'),
            'callback' => 'openabmma_showLicenses',
            'type' => MENU_CALLBACK
            );

    }
    else
    {
        $items[] = array(
            'path' => 'roles/delete/' . arg(2),
            'title' => t('Delete role'),
            'description' => "",
            'access' => user_access ('administer content'),
            'callback' => 'openabmma_deleteRole',
            'callback arguments' => array(arg(2)),
            'type' => MENU_CALLBACK
            );

        $items[] = array(
            'path' => 'licenses/delete/' . arg(2),
            'title' => t('Delete license'),
            'description' => "",
            'access' => user_access ('administer content'),
            'callback' => 'openabmma_deleteLicense',
            'callback arguments' => array(arg(2)),
            'type' => MENU_CALLBACK
            );

        $items[] = array(
            'path' => 'mymodels/' . arg(1) . '/addFiles',
            'title' => t('Files'),
            'description' => "",
            'access' => user_access ('access content'),
            'callback' => 'openabmma_addFiles',
            'callback arguments' => array(arg(1)),
            'type' => MENU_CALLBACK
            );

        $items[] = array(
            'path' => 'mymodels/' . arg(1) . '/members',
            'title' => t('Project members'),
            'description' => "",
            'access' => user_access ('access content'),
            'callback' => 'openabmma_manageMembers',
            'callback arguments' => array(arg(1)),
            'type' => MENU_CALLBACK
            );

        $items[] = array(
            'path' => 'mymodels/' . arg(1),
            'title' => t('My projects'),
            'description' => "",
            'access' => user_access ('access content'),
            'callback' => 'openabmma_openProject',
            'callback arguments' => array(arg(1)),
            'type' => MENU_CALLBACK
            );
    }

    return $items;
}

function openabmma_addFiles ($id='')
{
	return "";
}

function openabmma_manageMembers ($id='')
{
	if ($id == '')
		drupal_goto ("models");

	$output = "<br/><u>Owner</u>: " . openabmma_getModelOwner ($id);

	$members = openabmma_getModelMembers ($id);
	return $output;
}

function openabmma_getModelMembers ($id='')
{
	if ($id == '')
		return "";


	$result = db_query ("SELECT name FROM users A WHERE uid IN (SELECT user_id FROM openabm_model_project_member B WHERE id= (SELECT id FROM openabm_model_project WHERE name='%s'))", $id);
	while ($node = db_fetch_object ($result))
	{
		$output .= $node->name . "+" . $node->role . "-";
	}
	return $output;
}

function openabmma_getModelOwner ($id='')
{
	if ($id == '')
		return "";

	$result = (array) db_fetch_object (db_query ("SELECT name FROM users WHERE uid = (SELECT owner_uid FROM openabm_model_project WHERE name='%s')", $id));
	$owner = $result['name'];
	return $owner;
}

function openabmma_openProject ($id='')
{
	if ($id == '')
		drupal_goto ("models");

	$output .= "<br/>" . l ("View/download files in this project", "mymodels/" . $id . "/files");
	$output .= "<br/>" . l ("Add files to this project", "mymodels/" . $id . "/addFiles");
	$output .= "<br/>" . l ("Manage members in this project", "mymodels/" . $id . "/members");

	return $output;
}

function openabmma_showProjects ()
{
	global $user;

	$count = 0;
	$output .= '<br/><u>Owned projects:</u><br/>&nbsp;';
	$query = "SELECT name, description, visible FROM openabm_model_project WHERE owner_uid=%d";
	$result = db_query ($query, $user->uid);
	while ($node = db_fetch_object ($result))
	{
		$count++;
		$output .= "<br/><b>" . l ($node->name, "mymodels/" . $node->name) . "</b>&nbsp;";

		if ($node->visible == 1)	$output .= "[Public]";
		else				$output .= "[Private]";

		$output .= "&nbsp;<br/><small>" . $node->description . "</small><br/><small>";
		$output .= "</small><br/>";
	}

	$output .= "Total " . $count . " owned projects.<br/>&nbsp;<br/>";
	$count = 0;

	$output .= '<br/><u>Membered projects:<br/></u>&nbsp;<br/>';
	$query = "SELECT A.name, A.description, A.visible, B.role FROM openabm_model_project A JOIN openabm_model_project_member B WHERE B.user_id=%d";
	$result = db_query ($query, $user->uid);
	while ($node = db_fetch_object ($result))
	{
		$count++;
		$output .= "<b>" . l ($node->name, "mymodels/" . $node->name) . "</b>&nbsp;";

		if ($node->visible == 1)	$output .= "[Public]";
		else				$output .= "[Private]";

		$output .= "&nbsp;<br/><small>" . $node->description . "</small><br/><small>";
		$output .= "</small><br/>";
	}

	$output .= "Total " . $count . " membered projects.<br/>&nbsp;<br/>";
	$output .= "<br/>" . l ("To add new project, click here", "models/add");
	return $output;
}

function openabmma_showRoles ()
{
	$count = 0;
	$query = "SELECT id, name FROM openabm_role";
	$result = db_query ($query);
	while ($node = db_fetch_object ($result))
	{
		$count++;
		$output .= "<br/><b>" . $node->name . "</b>&nbsp;" . l ("[delete]", "roles/delete/" . $node->id);
	}

	$output = "<br/>Total " . $count . " role(s).<br/>" . $output . "<br/>&nbsp;" . drupal_get_form (openabmma_add_role);
	return $output;
}

function openabmma_add_role_submit ($form_id, $edit)
{
	$query = "INSERT INTO openabm_role (name) VALUES ('%s')";
	db_query ($query, $edit ['name']);
	drupal_goto ("roles");
}

function openabmma_add_role ()
{
	$form["details"] = array(
		"#type" => 'fieldset',
		"#collapsible" => FALSE,
		"#collapsed" => FALSE,
		"#title" => null,
		"#description" => t("You can add a new member role here."),
	);

	$form ["details"]["name"] = array (
		"#type" => "textfield",
		"#title" => t("Role name:"),
		"#default_value" => null,
		"#description" => "",
		"#maxlength" => 210,
		"#required" => true
	);

	$form ["details"]["submit"] = array (
		"#type" => "submit",
		"#value" => t("Submit"),
		"#submit" => TRUE
	);

	return ($form);
}

function openabmma_showLicenses ()
{
	$count = 0;
	$output = '';
	$query = "SELECT id, license, url FROM openabm_license";
	$result = db_query ($query);
	while ($node = db_fetch_object ($result))
	{
		$count++;
		$output .= "<b>" . $node->license . "</b>&nbsp;<small>" . l ("[delete this]", "licenses/delete/" . $node->id) . "<br/>" . l($node->url, $node->url) . "</small><br/>&nbsp;<br/>";
	}

	return "There are currently " . $count . " license(s). <br/>&nbsp;<br/>" . $output . "<hr/><br/>" . drupal_get_form(openabmma_addLicense_form);
}

function openabmma_deleteLicense ($id='')
{
	if ($id != "")
	{
		$query = "DELETE FROM openabm_license WHERE id=%d";
		db_query ($query, $id);
	}

	drupal_goto ("licenses");	
	return '';
}

function openabmma_deleteRole ($id='')
{
	if ($id != "")
	{
		$query = "DELETE FROM openabm_role WHERE id=%d";
		db_query ($query, $id);
	}

	drupal_goto ("roles");
	return '';
}

function openabmma_addLicense_form_submit ($formid, $edit)
{
	$query = "INSERT INTO openabm_license (license, url) VALUES ('%s', '%s')";
	db_query ($query, $edit['name'], $edit ['url']);
}

function openabmma_addLicense_form ()
{
	$form["details"] = array(
		"#type" => 'fieldset',
		"#collapsible" => FALSE,
		"#collapsed" => FALSE,
		"#title" => null,
		"#description" => t("You can add a new license type here."),
	);

	$form ["details"]["name"] = array (
		"#type" => "textfield",
		"#title" => t("License Name:"),
		"#default_value" => null,
		"#description" => t("Name of the license"),
		"#maxlength" => 210,
		"#required" => true
	);

	$form ["details"]["url"] = array (
		"#type" => "textfield",
		"#title" => t("URL:"),
		"#default_value" => null,
		"#description" => t("Web address of license document"),
		"#maxlength" => 210,
		"#required" => true
	);

	$form ["details"]["submit"] = array (
		"#type" => "submit",
		"#value" => t("Submit"),
		"#submit" => TRUE
	);

	return ($form);
}

function openabmma_settings_form() {
    $form['openabmma_settings'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Testing'),
        '#options' => node_get_types('names'),
        '#default_value' => 'story',
        '#description' => t('Some description'),
        );
    $form['array_filter'] = array('#type' => 'hidden');
    return system_settings_form($form);
}

function openabmma_newModel ($edit=null, $item=0)
{
	global $user;

	$result = (array) db_fetch_object (db_query ("SELECT max(id) FROM openabm_model_project"));
	$id = $result['max(id)'] + 1;

	$form["details"] = array(
		"#type" => 'fieldset',
		"#collapsible" => FALSE,
		"#collapsed" => FALSE,
		"#title" => null,
		"#description" => t("You can set the project properties here."),
	);

/*	$form ["details"]["proj_id"] = array (
		"#type" => "item",
		"#title" => t("Project ID:"),
		"#value" => $id,
		"#description" => t("Unique id for this project"),
	);
*/
	$form ["details"]["proj_ownerId"] = array (
		"#type" => "item",
		"#title" => t("Owner ID:"),
		"#value" => "#" . $user->uid . " - " . $user->name,
		"#description" => t("Information about the owner of this project"),
	);

	$form ["details"]["proj_name"] = array (
		"#type" => "textfield",
		"#title" => t("Project Name:"),
		"#default_value" => $edit ["proj_name"],
		"#description" => null,
		"#maxlength" => 210,
//		'#autocomplete_path' => 'user/autocomplete',
		"#required" => true
	);

	$form ["details"]["proj_description"] = array (
		"#type" => "textarea",
		"#title" => t("Description of project:"),
		"#default_value" => $edit ["proj_description"],
		"#description" => null,
		"#required" => false
	);

	$licenseTypes = array ();
	$result = db_query ("SELECT id, license, url FROM openabm_license");
	while ($node = db_fetch_object ($result))
		$licenseTypes [$node->id] = $node->license . " [" . $node->url . "]";

	$form ["details"]["proj_licenseId"] = array (
		"#type" => "select",
		"#title" => t("License:"),
		"#default_value" => $edit ["proj_licenseId"],
		"#options" => $licenseTypes,
		"#description" => null
	);

	$form["details"]["proj_visibility"] = array(
	'#type' => 'checkboxes',
	'#title' => t(''),
	'#default_value' => "false",
	'#options' => array(
		'visibility' => t('I want to make my project visible to all'),
		),
	'#description' => t('Enabling this option will make your project visible to all registered users of this site.'),
	);

	$form ["details"]["submit"] = array (
		"#type" => "submit",
		"#value" => t("Submit"),
		"#submit" => TRUE
	);

	return $form;
}

function openabmma_newModel_submit ($form_id, $edit)
{
	global $user;
	$query = "INSERT INTO openabm_model_project (owner_uid, name, description, visible, license_id) VALUES (%d, '%s', '%s', %d, %d)";
	db_query ($query, $user->uid, $edit ['proj_name'], $edit ['proj_description'], $edit ["proj_visibility"], $edit ['proj_licenseId']);
	drupal_goto ("models");
}
